### ISSUE TITLE
How would you add multiple loaders with individual options for each one?

### ISSUE THREAD

**Issue by gplusdotgr** [JonathanMH/webpack-scss-sass-file#2]
Here's where I am:  
```javascript
module: {
    rules: [
      {
        test: /\.s[ac]ss$/,
        use: ExtractTextPlugin.extract({
          use: {
            loader: "sass-loader",
            options: {
              sourceMap: true,
              includePath: "./node_modules/bootstrap-sass/assets/stylesheets"
            }
          },
        })
      }
    ]
  },
```

But with this pattern in mind, how do you add more loaders ( we need css-loader, sass-loader, postcss-loader ..) but with adding more options for every loader individually?

**Comment by JonathanMH** [comment]
Hi @gkatsanos!

I would probably test for `test: /\.sass$/`, `test: /\.css$/` and other seperately, so basically just copy the rule and exchange the test and loader parts, then you can define custom options for every one of them

**Comment by gplusdotgr** [comment]
Hey, so the solution was making "use" an array of objects instead of an object :) 
```
use: [
            {
              loader: "css-loader",
              options: {
                importLoaders:  1,
                sourceMap: true
              }
            },
            {
              loader: "sass-loader",
              options: {
                sourceMap: true,
                includePaths: [
                  path.resolve(__dirname, './node_modules/bootstrap-sass/assets/stylesheets'),
                ]
              }
            },
          ],
```

**Comment by JonathanMH** [comment]
@gkatsanos Oh, that looks good!

I have added a small example in the latest commit too https://github.com/JonathanMH/webpack-scss-sass-file/commit/6da4fbf5c112392cb4740d12711e615c603e6b41

**Comment by gplusdotgr** [comment]
@JonathanMH the important part is the part above that :)
