### ISSUE TITLE
webpack rules

### ISSUE THREAD

**Issue by marabesi** [JonathanMH/webpack-scss-sass-file#3]
Hellos @JonathanMH , 

thank you very much for this repo. I've had the same problem and this repo was incredibly helpful.

Though, I could understand why do we need to have two loaders.

```
    { // regular css files
        test: /\.css$/,
        loader: ExtractTextPlugin.extract({
          loader: 'css-loader?importLoaders=1',
        }),
      },
      { // sass / scss loader for webpack
        test: /\.(sass|scss)$/,
        loader: ExtractTextPlugin.extract(['css-loader', 'sass-loader'])
      }
```

The sass is the loaders which will be responsible to compile the sass, right?

What about the css loader? Is it to create the .css file only?

**Comment by JonathanMH** [comment]
Thanks!
The css one is optional, it was written in because of a previous issue and somebody wondering how :)
