### ISSUE TITLE
add bootstrap to project?

### ISSUE THREAD

**Issue by turcuciprian** [JonathanMH/webpack-scss-sass-file#6]
Hi, How would you add bootstrap to the project if you want to add just the css file?

You add it to packages.json as a dependency, npm update and then you use the node_modules/boostrap/dist/bootstrap.min.css to include the file? If yes, where (in what file and how) do I include it?

Is there a easier way?

**Comment by JonathanMH** [comment]
Hi @turcuciprian! Thanks for asking. I suggest you check out the answers on this github issue, especially the ones about `includPaths`: https://github.com/webpack-contrib/sass-loader/issues/366

Alternatively, you can always include bootstrap from the main scss file (something like `../../node_modules/and/so/on`): http://sass-lang.com/guide#topic-5

**Comment by JonathanMH** [comment]
@turcuciprian Did that help? Really curious over here!

**Comment by turcuciprian** [comment]
no, I did a lot of research and made my own built for adding bootstrap and my own code.  But thanks any way!

**Comment by JonathanMH** [comment]
@turcuciprian Alright, would love to see your solution too, maybe it's something I haven't thought of :)

**Comment by turcuciprian** [comment]
check out https://github.com/turcuciprian/gulpGenerator/blob/master/webpack.config.js ;)

**Comment by JonathanMH** [comment]
@turcuciprian Thanks! I was very lost when looking at it at first, but it seems like https://github.com/bootstrap-vue/bootstrap-vue is a pretty cool project!

Best of luck with your endeavors!

**Comment by turcuciprian** [comment]
hey @JonathanMH , Thanks!
I'm actually trying right now to integrate bootstrap vue in that config I gave you previously. Not sure what's not working, but I'm not able to make a tab panel style as per example.
